title: "John Doe's Home Page"
description: "John Doe's Home Page"
show-clock: true            # 是否显示日期/时间 / whether to show date/time
open-app-new-tab: true      # 应用卡片是否在新标签页打开 / whether to open app cards in a new tab
open-bookmark-new-tab: true # 书签是否在新标签页打开 / whether to open bookmarks in a new tab

footer:
  enabled: true
  text: "由 <a href='https://github.com/7ac9d42/vercel-flare' target='_blank'>Vercel-Flare</a> ❤️ 强力驱动"